// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Data;

#nullable disable

namespace QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BacSi", b =>
                {
                    b.Property<int>("MaBacSi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBacSi"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiKham")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBacSi");

                    b.HasIndex("MaChuyenKhoa");

                    b.ToTable("BacSis");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.ChuyenKhoa", b =>
                {
                    b.Property<int>("MaChuyenKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenKhoa"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChuyenKhoa");

                    b.HasIndex("TenChuyenKhoa")
                        .IsUnique();

                    b.ToTable("ChuyenKhoas");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.LichKham", b =>
                {
                    b.Property<int>("MaLichKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichKham"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongDaDangKy")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaLichKham");

                    b.HasIndex("MaBacSi");

                    b.ToTable("LichKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.PhieuDangKyKham", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("LyDoKham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaLichKham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaLichKham");

                    b.ToTable("PhieuDangKyKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BacSi", b =>
                {
                    b.HasOne("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("BacSis")
                        .HasForeignKey("MaChuyenKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BenhNhan", b =>
                {
                    b.HasOne("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("BenhNhan")
                        .HasForeignKey("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BenhNhan", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.LichKham", b =>
                {
                    b.HasOne("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BacSi", "BacSi")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.PhieuDangKyKham", b =>
                {
                    b.HasOne("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BenhNhan", "BenhNhan")
                        .WithMany("PhieuDangKyKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.LichKham", "LichKham")
                        .WithMany("PhieuDangKyKhams")
                        .HasForeignKey("MaLichKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("LichKham");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BacSi", b =>
                {
                    b.Navigation("LichKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.BenhNhan", b =>
                {
                    b.Navigation("PhieuDangKyKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.LichKham", b =>
                {
                    b.Navigation("PhieuDangKyKhams");
                });

            modelBuilder.Entity("QuanLyPhongKham_UNETI_05_DHTI17A1Hn.Models.TaiKhoan", b =>
                {
                    b.Navigation("BenhNhan");
                });
#pragma warning restore 612, 618
        }
    }
}
